[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

[dev]
  functions = "server" # Directory where Netlify functions (if any) are stored

[build.environment]
  NODE_VERSION = "16" # or the version you are using
